## Import Libraries

In [1]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("nextgen.db")

print("Database created")

Database created

## Create Database Connection

In [2]:
conn = sqlite3.connect("nextgen.db")

## Create Applicants Table

In [16]:
import pandas as pd
import sqlite3

conn = sqlite3.connect("nextgen.db")


# Applicants Table

applicants = pd.DataFrame({
    "applicant_id": [1,2,3,4,5,6,7,8,9,10],
    "name": [
        "Ali","Sara","Ahmed","Ayesha","Usman",
        "Hina","Bilal","Zain","Fatima","Hamza"
    ],
    "domain": [
        "Data Science",
        "Web Development",
        "Data Science",
        "AI",
        "Web Development",
        "AI",
        "Data Science",
        "AI",
        "Web Development",
        "Data Science"
    ],
    "university": [
        "LGU","PU","UET","LGU","PU",
        "UET","LGU","PU","UET","LGU"
    ],
    "application_date": [
        "2026-01-01","2026-01-02","2026-01-03",
        "2026-01-04","2026-01-05","2026-01-06",
        "2026-01-07","2026-01-08","2026-01-09",
        "2026-01-10"
    ],
    "status": [
        "Selected",
        "Selected",
        "Rejected",
        "Selected",
        "Selected",
        "Rejected",
        "Selected",
        "Selected",
        "Rejected",
        "Selected"
    ]
})


applicants.to_sql(
    "applicants",
    conn,
    if_exists="replace",
    index=False
)



# Interns Table

interns = pd.DataFrame({

    "intern_id":[101,102,103,104,105,106],

    "applicant_id":[1,2,4,5,7,10],

    "domain":[
        "Data Science",
        "Web Development",
        "AI",
        "Web Development",
        "Data Science",
        "Data Science"
    ],

    "start_date":[
        "2026-02-01",
        "2026-02-01",
        "2026-02-02",
        "2026-02-02",
        "2026-02-03",
        "2026-02-03"
    ],

    "completion_status":[
        "Completed",
        "Completed",
        "Completed",
        "Dropped Out",
        "Completed",
        "Completed"
    ]

})


interns.to_sql(
    "interns",
    conn,
    if_exists="replace",
    index=False
)



# Hackathon Scores Table

scores = pd.DataFrame({

    "intern_id":[101,102,103,105,106],

    "score":[
        92,
        85,
        88,
        95,
        90
    ],

    "domain":[
        "Data Science",
        "Web Development",
        "AI",
        "Data Science",
        "Data Science"
    ]

})


scores.to_sql(
    "hackathon_scores",
    conn,
    if_exists="replace",
    index=False
)


print("All 3 tables created successfully!")

conn.close()

All 3 tables created successfully!

In [21]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("nextgen.db")

print(pd.read_sql("SELECT * FROM applicants LIMIT 5", conn))

print(pd.read_sql("SELECT * FROM interns LIMIT 5", conn))

print(pd.read_sql("SELECT * FROM hackathon_scores LIMIT 5", conn))

   applicant_id    name           domain university application_date    status
0             1     Ali     Data Science        LGU       2026-01-01  Selected
1             2    Sara  Web Development         PU       2026-01-02  Selected
2             3   Ahmed     Data Science        UET       2026-01-03  Rejected
3             4  Ayesha               AI        LGU       2026-01-04  Selected
4             5   Usman  Web Development         PU       2026-01-05  Selected
   intern_id  applicant_id           domain  start_date completion_status
0        101             1     Data Science  2026-02-01         Completed
1        102             2  Web Development  2026-02-01         Completed
2        103             4               AI  2026-02-02         Completed
3        104             5  Web Development  2026-02-02       Dropped Out
4        105             7     Data Science  2026-02-03         Completed
   intern_id  score           domain
0        101     92     Data Science
1        102     85  Web Development
2        103     88               AI
3        105     95     Data Science
4        106     90     Data Science

In [22]:
applicants = pd.DataFrame({

    "applicant_id":[1,2,3,4,5,6,7,8,9,10],

    "name":[
        "Ali","Sara","Ahmed","Ayesha","Hassan",
        "Zain","Fatima","Usman","Hina","Bilal"
    ],

    "domain":[
        "Data Science",
        "AI",
        "Web Development",
        "Data Science",
        "AI",
        "Web Development",
        "Data Science",
        "AI",
        "Web Development",
        "Data Science"
    ],

    "university":[
        "LGU","PU","UET","LGU","FAST",
        "PU","LGU","FAST","UET","LGU"
    ],

    "application_status":[
        "Selected",
        "Selected",
        "Rejected",
        "Selected",
        "Selected",
        "Rejected",
        "Selected",
        "Selected",
        "Rejected",
        "Selected"
    ]
})


applicants

   applicant_id    name           domain university application_status
0             1     Ali     Data Science        LGU           Selected
1             2    Sara               AI         PU           Selected
2             3   Ahmed  Web Development        UET           Rejected
3             4  Ayesha     Data Science        LGU           Selected
4             5  Hassan               AI       FAST           Selected
5             6    Zain  Web Development         PU           Rejected
6             7  Fatima     Data Science        LGU           Selected
7             8   Usman               AI       FAST           Selected
8             9    Hina  Web Development        UET           Rejected
9            10   Bilal     Data Science        LGU           Selected

## Create Interns Table

In [23]:
interns = pd.DataFrame({

    "intern_id":[101,102,103,104,105,106],

    "applicant_id":[1,2,4,5,7,8],

    "domain":[
        "Data Science",
        "AI",
        "Data Science",
        "AI",
        "Data Science",
        "AI"
    ],

    "completion_status":[
        "Completed",
        "Completed",
        "Completed",
        "Dropped Out",
        "Completed",
        "Completed"
    ]

})


interns

   intern_id  applicant_id        domain completion_status
0        101             1  Data Science         Completed
1        102             2            AI         Completed
2        103             4  Data Science         Completed
3        104             5            AI       Dropped Out
4        105             7  Data Science         Completed
5        106             8            AI         Completed

## Create Hackathon Scores Table

In [24]:
hackathon_scores = pd.DataFrame({

    "intern_id":[101,102,103,105,106],

    "score":[90,88,76,95,82],

    "domain":[
        "Data Science",
        "AI",
        "Data Science",
        "Data Science",
        "AI"
    ]

})


hackathon_scores

   intern_id  score        domain
0        101     90  Data Science
1        102     88            AI
2        103     76  Data Science
3        105     95  Data Science
4        106     82            AI

## Save Tables into SQLite Database

In [25]:
applicants.to_sql(
    "applicants",
    conn,
    if_exists="replace",
    index=False
)


interns.to_sql(
    "interns",
    conn,
    if_exists="replace",
    index=False
)


hackathon_scores.to_sql(
    "hackathon_scores",
    conn,
    if_exists="replace",
    index=False
)

print("Tables Created Successfully")

Tables Created Successfully

## Explore Applicants Table

In [26]:
pd.read_sql(
    "SELECT * FROM applicants LIMIT 5;",
    conn
)

   applicant_id    name           domain university application_status
0             1     Ali     Data Science        LGU           Selected
1             2    Sara               AI         PU           Selected
2             3   Ahmed  Web Development        UET           Rejected
3             4  Ayesha     Data Science        LGU           Selected
4             5  Hassan               AI       FAST           Selected

## Explore Interns Table

In [27]:
pd.read_sql(
    "SELECT * FROM interns LIMIT 5;",
    conn
)

   intern_id  applicant_id        domain completion_status
0        101             1  Data Science         Completed
1        102             2            AI         Completed
2        103             4  Data Science         Completed
3        104             5            AI       Dropped Out
4        105             7  Data Science         Completed

## Explore Hackathon Scores Table

In [28]:
pd.read_sql(
    "SELECT * FROM hackathon_scores LIMIT 5;",
    conn
)

   intern_id  score        domain
0        101     90  Data Science
1        102     88            AI
2        103     76  Data Science
3        105     95  Data Science
4        106     82            AI

## PART A — SQL QUERIES

## 1. Completed Interns Per Domain

In [29]:
query1 = """

-- Counts completed interns grouped by domain

SELECT 
domain,
COUNT(*) AS completed_count

FROM interns

WHERE completion_status='Completed'

GROUP BY domain

ORDER BY completed_count DESC;

"""


pd.read_sql(query1,conn)

         domain  completed_count
0  Data Science                3
1            AI                2

## 2. Average Hackathon Score

In [30]:
query2 = """

-- Calculates average hackathon score per domain

SELECT

domain,

ROUND(AVG(score),2) AS avg_score

FROM hackathon_scores

GROUP BY domain

ORDER BY avg_score DESC;

"""


pd.read_sql(query2,conn)

         domain  avg_score
0  Data Science       87.0
1            AI       85.0

## 3. Top Performers Using JOIN

In [31]:
query3 = """

-- Finds interns scoring above 85

SELECT

i.intern_id,

i.domain,

h.score

FROM interns i

JOIN hackathon_scores h

ON i.intern_id=h.intern_id

WHERE h.score >= 85

ORDER BY h.score DESC;

"""


pd.read_sql(query3,conn)

   intern_id        domain  score
0        105  Data Science     95
1        101  Data Science     90
2        102            AI     88

## 4. Conversion Rate Using LEFT JOIN

In [32]:
query4 = """

-- Calculates applicant to completed intern conversion rate

SELECT

a.domain,

COUNT(DISTINCT a.applicant_id) AS total_applicants,

COUNT(DISTINCT i.intern_id) AS total_completed,


ROUND(

100.0 *
COUNT(DISTINCT i.intern_id)
/
COUNT(DISTINCT a.applicant_id),

2

) AS conversion_rate_pct


FROM applicants a


LEFT JOIN interns i

ON a.applicant_id=i.applicant_id

AND i.completion_status='Completed'


GROUP BY a.domain;


"""


pd.read_sql(query4,conn)

            domain  total_applicants  total_completed  conversion_rate_pct
0               AI                 3                2                66.67
1     Data Science                 4                3                75.00
2  Web Development                 3                0                 0.00

## 5. Dropout vs Completed

In [33]:
query5 = """

-- Shows completed and dropout interns per domain

SELECT

domain,

completion_status,

COUNT(*) AS total_interns


FROM interns


GROUP BY domain,completion_status;


"""


pd.read_sql(query5,conn)

         domain completion_status  total_interns
0            AI         Completed              2
1            AI       Dropped Out              1
2  Data Science         Completed              3

## Save Database

In [34]:
conn.close()

print("Database Saved Successfully")

Database Saved Successfully

In [35]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("nextgen.db")

print(pd.read_sql("SELECT name FROM sqlite_master WHERE type='table'", conn))

               name
0        applicants
1           interns
2  hackathon_scores